# Generated by Django 5.1.3 on 2024-12-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_flashsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashsale',
            name='discount_percentage',
            field=models.PositiveIntegerField(),
        ),
    ]
